# -*- coding: utf-8 -*-
"""Black_Box.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qbgfxSs_mTGTnBbBaP87YqOEuOYKxOu-

### Opening the black box

### eli5
"""

import eli5
eli5.show_weights(random_forest, feature_names=features)

"""### SHAP"""

import shap
shap_values = shap.TreeExplainer(random_forest).shap_values(X_rus)
shap.summary_plot(shap_values, X_rus, plot_type="bar", feature_names=features)

"""### LIME"""

import lime
predict_fn_xgb = lambda x: random_forest.predict_proba(x).astype(float)

explainer = lime.lime_tabular.LimeTabularExplainer(X_rus, feature_names=features, kernel_width=3)
observation_1 = 2
exp = explainer.explain_instance(X_rus[observation_1], predict_fn_xgb, num_features=6) 
exp.show_in_notebook(show_all=False)